version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build -- --prod
  post_build:
    commands:
      - aws s3 sync dist/ s3://aws-first-bucket-front-end